let
    Source = Json.Document(Web.Contents("https://api.meraki.com/api/v1/organizations/<orgid>/networks", [Headers=[#"X-Cisco-Meraki-API-Key"= ApiKeyMeraki]])),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "organizationId", "name", "productTypes", "timeZone", "tags", "enrollmentString", "url", "notes", "isBoundToConfigTemplate", "isVirtual"}, {"id", "organizationId", "name", "productTypes", "timeZone", "tags", "enrollmentString", "url", "notes", "isBoundToConfigTemplate", "isVirtual"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Expanded Column1",{{"id", type text}, {"organizationId", Int64.Type}, {"name", type text}, {"productTypes", type any}, {"timeZone", type text}, {"tags", type any}, {"enrollmentString", type any}, {"url", type text}, {"notes", type any}, {"isBoundToConfigTemplate", type logical}, {"isVirtual", type logical}}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Changed Type", "Text Before Delimiter", each Text.BeforeDelimiter([name], "-"), type text),
    #"Renamed Columns" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "Site"}})
in
    #"Renamed Columns"
