let
    // API Key securely passed to the header
    Source = Json.Document(
        Web.Contents(
            "https://api.meraki.com/api/v1/organizations", 
            [Headers = [#"X-Cisco-Meraki-API-Key" = ApiKeyMeraki]]
        )
    ),
    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Expanded Column1" = Table.ExpandRecordColumn(#"Converted to Table", "Column1", {"id", "name", "url", "api", "licensing", "cloud", "management"}, {"id", "name", "url", "api", "licensing", "cloud", "management"}),
    #"Expanded api" = Table.ExpandRecordColumn(#"Expanded Column1", "api", {"enabled"}, {"api.enabled"}),
    #"Expanded licensing" = Table.ExpandRecordColumn(#"Expanded api", "licensing", {"model"}, {"licensing.model"}),
    #"Expanded cloud" = Table.ExpandRecordColumn(#"Expanded licensing", "cloud", {"region"}, {"cloud.region"}),
    #"Expanded cloud.region" = Table.ExpandRecordColumn(#"Expanded cloud", "cloud.region", {"name", "host"}, {"cloud.region.name", "cloud.region.host"}),
    #"Expanded cloud.region.host" = Table.ExpandRecordColumn(#"Expanded cloud.region", "cloud.region.host", {"name"}, {"cloud.region.host.name"}),
    #"Expanded management" = Table.ExpandRecordColumn(#"Expanded cloud.region.host", "management", {"details"}, {"management.details"}),
    #"Expanded management.details" = Table.ExpandListColumn(#"Expanded management", "management.details"),
    #"Expanded management.details1" = Table.ExpandRecordColumn(#"Expanded management.details", "management.details", {"name", "value"}, {"management.details.name", "management.details.value"}),
    #"Changed Type" = Table.TransformColumnTypes(
        #"Expanded management.details1",
        {
            {"id", Int64.Type}, 
            {"name", type text}, 
            {"url", type text}, 
            {"api.enabled", type logical}, 
            {"licensing.model", type text}, 
            {"cloud.region.name", type text}, 
            {"cloud.region.host.name", type text}, 
            {"management.details.name", type text}, 
            {"management.details.value", Int64.Type}
        }
    )
in
    #"Changed Type"
